xlist_test: xlist_test.c ../../src/xharp.h ../../src/xexcept.* ../../src/xglobal_exceptions.c ../../src/xlist.*
	gcc xlist_test.c ../../src/xharp.h ../../src/xexcept.* ../../src/xglobal_exceptions.c ../../src/xlist.* -o xlist_test

