xqueue_test: xqueue_test.c ../../src/xharp.h ../../src/xexcept.* ../../src/xglobal_exceptions.c ../../src/xlist.* ../../src/xqueue.*
	gcc xqueue_test.c ../../src/xharp.h ../../src/xexcept.* ../../src/xglobal_exceptions.c ../../src/xlist.* ../../src/xqueue.* -o xqueue_test -Wall

